### ISSUE TITLE
Error running the test

### ISSUE THREAD

**Issue by paulovsm** [llSourcell/The-Neural-Qubit#3]
Hi, I'm trying to run your experiment but after a successful training (10K iterations) I'm getting an error to run the testing script. 

The error happens once the model is being loaded.

`Traceback (most recent call last):
  File "testing.py", line 226, in <module>
    saver.restore(session, checkpoint_string + 'sess.ckpt-' + str(ckpt_val))
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1755, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [6,2] rhs shape= [7,2]
	 [[Node: save/Assign_10 = Assign[T=DT_FLOAT, _class=["loc:@variables/Variable_4"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](variables/Variable_4, save/RestoreV2:10)]]

Caused by op 'save/Assign_10', defined at:
  File "testing.py", line 221, in <module>
    saver = tf.train.Saver(parameters)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1293, in __init__
    self.build()
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1302, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1339, in _build
    build_save=build_save, build_restore=build_restore)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 796, in _build_internal
    restore_sequentially, reshape)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 471, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 161, in restore
    self.op.get_shape().is_fully_defined())
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 280, in assign
    validate_shape=validate_shape)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 58, in assign
    use_locking=use_locking, name=name)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/anaconda3/envs/neuralqbit/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [6,2] rhs shape= [7,2]
	 [[Node: save/Assign_10 = Assign[T=DT_FLOAT, _class=["loc:@variables/Variable_4"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](variables/Variable_4, save/RestoreV2:10)]]`

I've tested with different checkpoints with no success (10000, 9000, 6000, 2000).

I'm using my Macbook with python 3.6, strawberryfields==0.10.0  and tensorflow==1.6.0

Is this a problem related to Tensorflow version that is not 1.3 as recommended?

**Comment by sidsidsidsid** [comment]
I'm seeing two issues with running testing.py. Any help would be appreciated?

Environment - Colab
Paackages - !pip install strawberryfields==0.10.0 tensorflow==1.6.0



[ISSUE 1] I set the colab envirnoment to use GPU, but I'm getting the below error?
"................2019-09-16 20:52:04.782244: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA......."


[ISSUE 2] I'm getting the same error as @paulovsm . It's failing in the testing.py 

code failing on this line --->>>> "....saver.restore(session, checkpoint_string + 'sess.ckpt-' + str(ckpt_val))...."

It appears that the shapes do not match when attempting to retrieve from the stored data.

NOTE ------->>>>> the below stack has line 249 in testing.py. But, I added print statements in the code. So the original code line is around 226.

----------------------------------------------------ERROR-------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [6,2] rhs shape= [7,2]
	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@variables/Variable_6"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](variables/Variable_6, save/RestoreV2:12)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testing.py", line 249, in <module>
    saver.restore(session, checkpoint_string + 'sess.ckpt-' + str(ckpt_val))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1755, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [6,2] rhs shape= [7,2]
	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@variables/Variable_6"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](variables/Variable_6, save/RestoreV2:12)]]

Caused by op 'save/Assign_12', defined at:
  File "testing.py", line 242, in <module>
    saver = tf.train.Saver(parameters)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1293, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1302, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1339, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 796, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 471, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 161, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 280, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 58, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [6,2] rhs shape= [7,2]
	 [[Node: save/Assign_12 = Assign[T=DT_FLOAT, _class=["loc:@variables/Variable_6"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](variables/Variable_6, save/RestoreV2:12)]]
